# Generated by Django 2.1.2 on 2018-11-03 13:33

import QuentinhaFood.models.estabelecimento
import QuentinhaFood.models.usuario
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_endereco', models.CharField(max_length=200)),
                ('numero_endereco', models.IntegerField()),
                ('complemento_endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_idcidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100, validators=[QuentinhaFood.models.estabelecimento.Estabelecimento.validate_phone])),
                ('telefone_estabelecimento', models.CharField(max_length=100, validators=[QuentinhaFood.models.estabelecimento.Estabelecimento.validate_phone])),
                ('telefoneAlternativo_estabelecimento', models.CharField(blank=True, max_length=100, null=True, validators=[QuentinhaFood.models.estabelecimento.Estabelecimento.validate_phone])),
                ('email_estabelecimento', models.EmailField(max_length=254)),
                ('site_estabelecimento', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_estabelecimento', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_estabelecimento', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_estabelecimento', models.CharField(blank=True, max_length=200, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.CharField(max_length=100)),
                ('adicionais_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('estabelecimento_idestabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoria_produto', models.CharField(max_length=100)),
                ('categoria_idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=100, validators=[QuentinhaFood.models.usuario.validate_cpf])),
                ('telefone_usuario', models.CharField(max_length=100, validators=[QuentinhaFood.models.usuario.validate_phone])),
                ('telefoneAlternativo_usuario', models.CharField(blank=True, max_length=100, null=True, validators=[QuentinhaFood.models.usuario.validate_phone])),
                ('apelido_usuario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='subCategoria_idsubCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.SubCategoria'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='nome_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Usuario'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario_idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Usuario'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado_idestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Estado'),
        ),
    ]
