# Generated by Django 2.1.2 on 2018-10-26 12:50

import QuentinhaFood.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=100, validators=[QuentinhaFood.models.usuario.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefoneAlternativo_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[QuentinhaFood.models.usuario.validate_phone]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_usuario',
            field=models.CharField(max_length=100, validators=[QuentinhaFood.models.usuario.validate_phone]),
        ),
    ]
