# Generated by Django 2.1.2 on 2018-11-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apelido_usuario',
        ),
    ]
