# Generated by Django 2.1.2 on 2018-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0002_remove_usuario_apelido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(default=0, upload_to='../static/images'),
            preserve_default=False,
        ),
    ]
