# Generated by Django 2.1.2 on 2018-10-26 12:59

import QuentinhaFood.models.estabelecimento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0002_auto_20181026_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(max_length=100, validators=[QuentinhaFood.models.estabelecimento.validate_phone]),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='facebook_estabelecimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='instagram_estabelecimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='site_estabelecimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefoneAlternativo_estabelecimento',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[QuentinhaFood.models.estabelecimento.validate_phone]),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone_estabelecimento',
            field=models.CharField(max_length=100, validators=[QuentinhaFood.models.estabelecimento.validate_phone]),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='twitter_estabelecimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
