# Generated by Django 2.1.2 on 2018-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0003_auto_20181026_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='adicionais_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
