# Generated by Django 2.1.2 on 2018-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0004_auto_20181026_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
