# Generated by Django 2.1.2 on 2018-11-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0005_auto_20181026_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='telefoneAlternativo_estabelecimento',
        ),
    ]
