# Generated by Django 2.1.2 on 2018-11-03 02:05

import QuentinhaFood.models.estabelecimento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0006_remove_estabelecimento_telefonealternativo_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='imagem_estabelecimento',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='telefoneAlternativo_estabelecimento',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[QuentinhaFood.models.estabelecimento.Estabelecimento.validate_phone]),
        ),
    ]
