# Generated by Django 2.1.2 on 2018-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0011_auto_20181110_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='imagem_estabelecimento',
            field=models.ImageField(default=1, upload_to='images/estabelecimento'),
            preserve_default=False,
        ),
    ]
