# Generated by Django 2.1.2 on 2018-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0012_estabelecimento_imagem_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(default=1, upload_to='images/produto'),
            preserve_default=False,
        ),
    ]
