# Generated by Django 2.1.2 on 2018-11-20 02:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0013_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='estabelecimento',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
