# Generated by Django 2.1.2 on 2018-11-18 13:25

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0015_estabelecimento_descricao_estabelecimento'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
