# Generated by Django 2.1.2 on 2018-11-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0016_auto_20181118_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuentinhaFood.Categoria'),
            preserve_default=False,
        ),
    ]
