# Generated by Django 2.1.2 on 2018-11-19 21:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QuentinhaFood', '0017_produto_categoria_idcategoria'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categoria',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategoria',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
